### ISSUE TITLE
Need to output answered/resolved ip to syslog

### ISSUE THREAD

**Issue by mattcowen** [dmachard/go-dnscollector#11]
At the moment it seems the answer is not accessible to the loggers. All I am seeing is the ip address of the forwarder DNS server when I want access to the resolved IP for the query. I can see Bind is sending this via dnstap but can't seem to get the syslog logger to output it. What am I missing?

**Comment by dmachard** [comment]
Can you share your config (bind and the collector) please ? Answered IP is only available with JSON format.

**Comment by mattcowen** [comment]
bind

         options {
              directory "/var/cache/bind";
      
              dnstap { all;  };
              dnstap-output unix "/var/cache/bind/dnstap.sock";
      
      
              // If there is a firewall between you and nameservers you want
              // to talk to, you may need to fix the firewall to allow multiple
              // ports to talk.  See http://www.kb.cert.org/vuls/id/800113
      
              // If your ISP provided one or more IP addresses for stable
              // nameservers, you probably want to use them as forwarders.
              // Uncomment the following block, and insert the addresses replacing
              // the all-0's placeholder.
      
              forwarders {
                168.63.129.16;
              };
      
              //========================================================================
              // If BIND logs error messages about the root key being expired,
              // you will need to update your keys.  See https://www.isc.org/bind-keys
              //========================================================================
              dnssec-validation auto;
              allow-query { any; };
              listen-on { any; };
              listen-on-v6 { any; };
      
              //querylog yes;
      
      };
      
      logging {
         category default { default_syslog; default_debug; };
         category unmatched { null; };
         channel default_syslog {
             syslog daemon;        // send to syslog
             severity info;        // only priority info and higher
         };
         channel default_debug {
             file "named.run";     // write to named.run in
                                   // the working directory
                                   // Note: stderr is used instead
                                   // of "named.run"
                                   // if the server is started
                                   // with the '-f' option.
             severity dynamic;     // log at the server's
                                   // current debug level
         };
         channel default_stderr {
             stderr;               // writes to stderr
             severity info;        // only priority info and higher
         };
         channel null {
             null;                 // toss anything sent to
                                   // this channel
         };
       };


config.yml

    collectors:
        dnstap:
          # to enable, set the enable to true
          enable: true
          # listen on ip
          listen-ip: 0.0.0.0
          # listening on port
          # listen-port: 6000
          # unix socket path
          sock-path: /var/cache/bind/dnstap.sock
          # tls support
          tls-support: false
          # certificate server file
          cert-file: ""
          # private key server file
          key-file: ""

**Comment by mattcowen** [comment]
And all i get is something like this

2021-11-20T12:55:20.033968899Z dns1 RESOLVER_RESPONSE NOERROR 0.0.0.0 59891 INET UDP 347b co.uk DNSKEY 0.000000
2021-11-20T12:55:20.033968899Z dns1 RESOLVER_QUERY NOERROR 0.0.0.0 45114 INET UDP 69b www.amazon.co.uk.edgekey.net A 0.000000
2021-11-20T12:55:20.069969364Z dns1 RESOLVER_QUERY NOERROR 0.0.0.0 39596 INET UDP 64b e15314.a.akamaiedge.net AAAA 0.000000
2021-11-20T12:55:20.037968951Z dns1 RESOLVER_RESPONSE NOERROR 0.0.0.0 45114 INET UDP 107b www.amazon.co.uk.edgekey.net A 0.004000
2021-11-20T12:55:20.073969415Z dns1 RESOLVER_RESPONSE NOERROR 0.0.0.0 39596 INET UDP 113b e15314.a.akamaiedge.net AAAA 0.004000
2021-11-20T12:55:20.065969312Z dns1 CLIENT_QUERY NOERROR 127.0.0.1 38139 INET UDP 41b e15314.a.akamaiedge.net AAAA 0.000000
2021-11-20T12:55:20.073969415Z dns1 CLIENT_RESPONSE NOERROR 127.0.0.1 38139 INET UDP 116b e15314.a.akamaiedge.net AAAA 0.008000


my syslog logger is

     syslog:
    # to enable, set the enable to true
    enable: true
    # Set the syslog logging severity
    severity: INFO
    # Set the syslog logging facility
    facility: DAEMON
    # Transport to use to a remote log daemon or local one
    # local|tcp|udp|unix
    transport: local
    # Remote address host:port
    remote-address: ""
    # output text format, please refer to the default text format to see all available directives
    # use this parameter if you want a specific format
    #text-format: "timestamp operation queryip qr qname qtype responseip"
    mode: json

**Comment by mattcowen** [comment]
@dmachard I downloaded the latest as well as tweaked my Azure monitor query. I see it working. 

Great tool, thank you very much for your efforts.
