### ISSUE TITLE
Feature request: Support for resolver label in prometheus logger

### ISSUE THREAD

**Issue by flz** [dmachard/go-dnscollector#124]
Hey,

I've started using the DNS sniffer collector which is working really well. I was wondering if there could be an option to add a label for what resolver is used in the metrics exposed by prometheus. I think the data is captured already (ResponseIP) but this would increase cardinality which is why I'm not convinced it should be enabled by default.

**Comment by dmachard** [comment]
The `stream_id` contains the name of your resolver identity (with dnstap collect), it's not sufficient?

**Comment by flz** [comment]
Maybe I misunderstand what QueryIP and ResponseIP are then.

My use case is to deploy the dns-sniffer (not dnstap) collector on a bunch of machines and get client-side DNS metrics. I don't necessarily control what resolvers they use through /etc/resolv.conf and being able to have per-resolver latency metrics for example gives me better visibility over resolver performance.

Hope this helps!

**Comment by dmachard** [comment]
The queryip is the source IP of the client and response IP should be the IP of the resolver.

2022-09-26T14:13:09.261751412Z denis-laptop CLIENT_QUERY NOERROR **192.168.1.17** 46767 **8.8.8.8** 53 INET UDP 54b www.google.fr A 0.000000
2022-09-26T14:13:09.278427556Z denis-laptop CLIENT_RESPONSE NOERROR **192.168.1.17** 46767 **8.8.8.8** 53 INET UDP 58b www.google.fr A 0.016676

I can add a  new setting parameter to add the label for response IP  (but not enabled by default ,you're right)

**Comment by dmachard** [comment]
by the way, feel free to make a pull request :)

**Comment by flz** [comment]
I'll try and take a stab at it when I get a chance. I haven't had to write golang code (yet) :-)

**Comment by dmachard** [comment]
implemented in release v0.35
