### ISSUE TITLE
missing rdata in answers

### ISSUE THREAD

**Issue by csszep** [dmachard/go-dnscollector#13]
Hi!

When i try to query gmail.com  MX  records i get:

dig @127.0.0.1 gmail.com MX

; <<>> DiG 9.16.22-Debian <<>> @127.0.0.1 gmail.com MX
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58347
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: dac713c60d021e8e01000000619dfbb31521462b3eaaf61d (good)
;; QUESTION SECTION:
;gmail.com.                     IN      MX

;; ANSWER SECTION:
gmail.com.              1916    IN      MX      10 alt1.gmail-smtp-in.l.google.com.
gmail.com.              1916    IN      MX      5 gmail-smtp-in.l.google.com.
gmail.com.              1916    IN      MX      40 alt4.gmail-smtp-in.l.google.com.
gmail.com.              1916    IN      MX      30 alt3.gmail-smtp-in.l.google.com.
gmail.com.              1916    IN      MX      20 alt2.gmail-smtp-in.l.google.com.

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 24 09:45:39 CET 2021
;; MSG SIZE  rcvd: 192

but in syslog json output there is no rdata:

{
  "operation": "CLIENT_RESPONSE",
  "identity": "dns-bind",
  "family": "INET",
  "protocol": "UDP",
  "query-ip": "127.0.0.1",
  "query-port": "49191",
  "response-ip": "127.0.0.1",
  "response-port": "-",
  "length": 276,
  "rcode": "NOERROR",
  "qname": "gmail.com",
  "qtype": "MX",
  "latency": "0.000000",
  "timestamp-rfc3339": "2021-11-24T08:33:03.922233802Z",
  "answers": [
    {
      "name": "gmail.com",
      "rdatatype": "MX",
      "ttl": 2672,
      "rdata": "-"
    },
    {
      "name": "gmail.com",
      "rdatatype": "MX",
      "ttl": 2672,
      "rdata": "-"
    },
    {
      "name": "gmail.com",
      "rdatatype": "MX",
      "ttl": 2672,
      "rdata": "-"
    },
    {
      "name": "gmail.com",
      "rdatatype": "MX",
      "ttl": 2672,
      "rdata": "-"
    },
    {
      "name": "gmail.com",
      "rdatatype": "MX",
      "ttl": 2672,
      "rdata": "-"
    }
  ],
  "country-isocode": "-"
}

bind9 native dnstap-output file:

type: MESSAGE
identity: dns-bind
version: bind
message:
  type: CLIENT_RESPONSE
  response_time: !!timestamp 2021-11-24T08:41:02Z
  message_size: 192b
  socket_family: INET
  socket_protocol: UDP
  query_address: 10.2.66.88
  response_address: 10.2.66.88
  query_port: 35263
  response_port: 0
  response_message_data:
    opcode: QUERY
    status: NOERROR
    id: 39250
    flags: qr rd ra
    QUESTION: 1
    ANSWER: 5
    AUTHORITY: 0
    ADDITIONAL: 1
    OPT_PSEUDOSECTION:
      EDNS:
        version: 0
        flags:
        udp: 1232
        COOKIE: fd13c2857898ee9d01000000619dfa9e9c7b03c68cfac6b7
    QUESTION_SECTION:
      - gmail.com. IN MX
    ANSWER_SECTION:
      - gmail.com. 2193 IN MX 5 gmail-smtp-in.l.google.com.
      - gmail.com. 2193 IN MX 20 alt2.gmail-smtp-in.l.google.com.
      - gmail.com. 2193 IN MX 10 alt1.gmail-smtp-in.l.google.com.
      - gmail.com. 2193 IN MX 40 alt4.gmail-smtp-in.l.google.com.
      - gmail.com. 2193 IN MX 30 alt3.gmail-smtp-in.l.google.com.
  response_message: |
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id:  39250
    ;; flags: qr rd ra    ; QUESTION: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 1232
    ; COOKIE: fd13c2857898ee9d01000000619dfa9e9c7b03c68cfac6b7
    ;; QUESTION SECTION:
    ;gmail.com.                 IN      MX

    ;; ANSWER SECTION:
    gmail.com.          2193    IN      MX      5 gmail-smtp-in.l.google.com.
    gmail.com.          2193    IN      MX      20 alt2.gmail-smtp-in.l.google.com.
    gmail.com.          2193    IN      MX      10 alt1.gmail-smtp-in.l.google.com.
    gmail.com.          2193    IN      MX      40 alt4.gmail-smtp-in.l.google.com.
    gmail.com.          2193    IN      MX      30 alt3.gmail-smtp-in.l.google.com.

**Comment by dmachard** [comment]
support for mx, cname, ptr, txt, srv, soa and ns added
it will be available in the next release
