### ISSUE TITLE
json log duplicates

### ISSUE THREAD

**Issue by RonV666** [dmachard/go-dnscollector#14]
using v0.10.0 or v0.11.0 go-collector binary with this config:

trace:
  verbose: false

collectors:
  dnstap:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 6000
    tls-support: false

loggers:
  logfile:
    enable: true
    file-path:  "/var/log/dnstap.log"
    max-size: 100
    max-files: 20
    mode: json

I am getting massive amounts of duplicates.  I also tried:

   syslog:
     enable: true
     severity: INFO
     facility: DAEMON
     transport: local
     # Remote address host:port
     # remote-address: ""
     # output text format, please refer to the default text format to see all available directives
     # use this parameter if you want a specific format
     # text-format: ""
     # output format: text|json
     mode: json

and curiously I am getting duplicates as well, however they are in a strange staircase format where the duplicate entry gets appended at the end of the previous one for 2-5 times.

any tips on how to troubleshoot this?

my source is dnsdist v1.5.1

using this as config:
--from https://dmachard.github.io/posts/0001-dnstap-testing/#tcp-stream
fsul = newFrameStreamTcpLogger("xxx.xxx.xxx.xxx:6000")
addAction(AllRule(), DnstapLogAction("dnsdist", fsul))
addResponseAction(AllRule(), DnstapLogResponseAction("dnsdist", fsul))
-- Cache Hits
addCacheHitResponseAction(AllRule(), DnstapLogResponseAction("dnsdist", fsul))

**Comment by dmachard** [comment]
can you share your log output please ?

**Comment by RonV666** [comment]
all below using v0.11.0:

using:
=====
loggers:
  logfile:
    enable: true
    file-path:  "/var/log/dnstap.log"
    max-size: 100
    max-files: 20
    mode: json


to run this test, I did two 'dig @dns peanut.com' and i logged 6 queries and 8 responses;

filename: 

logger-json.txt

[logger-json.txt](https://github.com/dmachard/go-dnscollector/files/7614457/logger-json.txt)

using syslog:
==========
   syslog:
     enable: true
     severity: INFO
     facility: DAEMON
     transport: local
     mode: json

twice with about 2-3 seconds;
 dig @172.25.25.2 peanut.com +short
104.207.247.51

then I grep for 'peanut.com' in my logfile and although I have only 8 lines or so, they are spectacularily long and contains other RR data;

filename: syslog-json.txt
[syslog-json.txt](https://github.com/dmachard/go-dnscollector/files/7614458/syslog-json.txt)

**Comment by RonV666** [comment]
I am wondering if its my dnsdist source that is the issue, as I installed dnstap_receiver using this config:

input:
  tcp-socket:
    # enable tls support
    tls-support: false

output:
   file:
    # enable or disable
    enable: true
    # format available text|json|yaml
    format: json
    # log file path or null to print to stdout
    file: /var/log/dnstap.log
    # max size for log file
    file-max-size: 20M
    # number of max log files
    file-count: 100

and a log generated shows tons of queries for a single dig to peanut.com:

filename: receiver.txt
[receiver.txt](https://github.com/dmachard/go-dnscollector/files/7614497/receiver.txt)

any tips are welcome, thanks

**Comment by RonV666** [comment]
Im seeing better results using the dnstap_receiver, but for some reason it doesnt log the returned RR, only the client and the query and response, but not the returned RR data (?).  I'm stuck!

**Comment by RonV666** [comment]
i was perplexed so as a test I installed a Fedora Server 35 machine to run the collector and I am seeing the same behaviour; a single DNS query generates duplicate CQ and CR entries for the same query.

I am going to try and wireshark the packets to make sure I am only getting one copy from the source, I believe there is a decoder for dnstap.

**Comment by dmachard** [comment]
Have you the same behavior with the text format ?

**Comment by dmachard** [comment]
Bug confirmed in my side. I push a fix

**Comment by RonV666** [comment]
my pleasure.  how can I test 0.12.0? :)

**Comment by dmachard** [comment]
v0.12.0 is available, waiting feedback to close this issue

**Comment by RonV666** [comment]
perhaps not related specifically to this fix but I am getting a crash. 

[0.12.0-crash.txt](https://github.com/dmachard/go-dnscollector/files/7626814/0.12.0-crash.txt)

**Comment by dmachard** [comment]
Can you open a new issue regarding this crash please ? i will investigate on it

**Comment by dmachard** [comment]
no more duplicate logs with the beta2 ?

**Comment by RonV666** [comment]
Hello @dmachard , I checked the logs and I have +-2 REQ vs RESPONSE in each logfile and no duplicates. seems quite good, thank you kindly for this fix
