### ISSUE TITLE
Feature request: Kafka as sink 

### ISSUE THREAD

**Issue by danielloader** [dmachard/go-dnscollector#177]
Would be nice to have Kafka as a intermediate data sink to act as a back pressure buffer or fanout for other sinks, elastic etc.

Will give more details if the idea interests you.

Did notice https://github.com/segmentio/kafka-go is in the go.sum, but that presumably is one of the downstream dependencies.

**Comment by dmachard** [comment]
Kafka support was planned, perhaps for next release but not sure.

**Comment by danielloader** [comment]
Thanks for the reply, there's no urgency if anything it's just a placeholder issue for other people to register interest and ideas too.

**Comment by dmachard** [comment]
If you have other ideas, feel free to create tickets :)

**Comment by gallypette** [comment]
Hi, it may be worthwhile to have a look at [benthos](https://github.com/benthosdev/benthos) for this use-case.

**Comment by danielloader** [comment]
Makes sense to re-use it if it can be embedded as a library, the sheer flexibility of output sinks would be hugely beneficial there.

**Comment by dmachard** [comment]
support is planned for next release

**Comment by dmachard** [comment]
beta release available, any feedback will be appreciated.

**Comment by dmachard** [comment]
Release v0.32.0 is out!
