### ISSUE TITLE
Possibility to configure output fields format.

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/go-dnscollector#2]
Hi there,

Thank you for this new wonderful application. I found for my self that it will be really great to have option to define output format for logs in configuration settings. 

Like as we have for nginx or apache server. 

Is it possible to implement it in new dnscollector?

**Comment by dmachard** [comment]
great idea!
I will take a look to see if it's complicated to implement or not.

**Comment by dmachard** [comment]
implemented in commit https://github.com/dmachard/go-dnscollector/commit/2ac93fbea2039b7e030e9398a19f43c20551ae58

the new default text format and all available directives

  # specific the default text log format used on all loggers supporting this mode
  # all directives availables:
  # - timestamp: timestamp rfc3339 format, with nano support
  # - identity: dnstap identity
  # - qr: query or reply flag
  # - operation: dnstap operation
  # - rcode: dns return code
  # - queryip: dns query ip
  # - queryport: dns query port
  # - responseip: dns response ip
  # - responseport: dns response port
  # - id: dns id
  # - family: ip protocol version INET or INET6
  # - protocol: protocol UDP, TCP
  # - length: the length of the query or reply
  # - qtype: dns qtype
  # - qname: dns qname
  # - latency: computed latency between queries and replies
  # - answercount: the number of answer
  # - country: country iso code
  # - ttl: answer ttl
  text-format: "timestamp identity qr operation rcode queryip queryport family protocol length qname qtype latency ttl"

**Comment by dmachard** [comment]
new release v0.6.0 available

**Comment by KVInventoR** [comment]
thank you, I will test it tomorrow
