### ISSUE TITLE
Replace identiy/identity in code

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/go-dnscollector#3]
Probably there are 2 mistakes in code and need replace  identiy to identity

as example here:
https://github.com/dmachard/go-dnscollector/blob/e503fc1d1ee84d45534de83309a4e142797a4bfd/dnsutils/message.go#L18

**Comment by dmachard** [comment]
thank to report this issue.
fix in commit https://github.com/dmachard/go-dnscollector/commit/c7a130dd7cdba7ce609d15ded608e53f2cb301a8

**Comment by dmachard** [comment]
new release v0.6.0 available

**Comment by KVInventoR** [comment]
thank you, I will test it tomorrow
