### ISSUE TITLE
Problem with netlib on FreeBSD. No SetSock_RCVBUF

### ISSUE THREAD

**Issue by borjam** [dmachard/go-dnscollector#332]
Trying to compile version 0.32 on FreeBSD 13.2 using both Go version 1.20.1 and 1.20.2,

```
go120 build
# github.com/dmachard/go-dnscollector/collectors
collectors/dnstap.go:287:34: undefined: netlib.SetSock_RCVBUF
collectors/powerdns.go:251:34: undefined: netlib.SetSock_RCVBUF

```

setsockopt() on FreeBSD does indeed include the relevant constants

```
           SO_SNDBUF          set buffer size for output
           SO_RCVBUF          set buffer size for input

```
Would it be a bug on Go's syscall module? However it doesn't complain when building the netlib module and I have seen that the relevant constants are defined for FreeBSD:

```
zerrors_freebsd_386.go:	SO_RCVBUF                         = 0x1002
zerrors_freebsd_amd64.go:	SO_RCVBUF                         = 0x1002
zerrors_freebsd_arm.go:	SO_RCVBUF                         = 0x1002
zerrors_freebsd_arm64.go:	SO_RCVBUF                         = 0x1002
zerrors_freebsd_riscv64.go:	SO_RCVBUF                         = 0x1002

```
Sorry if I knocked the wrong door.

**Comment by dmachard** [comment]
I think it's because of the following  golang build directives int the netlib/sock.go file
```
//go:build linux || darwin
// +build linux darwin
```
Can you try the PR https://github.com/dmachard/go-dnscollector/pull/334 ?
