### ISSUE TITLE
xdp sniffer has interface name hardcoded

### ISSUE THREAD

**Issue by danhanks** [dmachard/go-dnscollector#336]
https://github.com/dmachard/go-dnscollector/blob/da8c5ecab45cfcb11ecbf2d55fc8392b4f6f4614/collectors/sniffer_xdp.go#L114

Was trying to use the xdp sniffer, but kept running into errors like this:
`ERROR: 2023/06/09 12:51:16.565618 [xdp] collector=xdp - lookup network iface: route ip+net: no such network interface`
I suspect because the interface name is hard-coded here.

**Comment by dmachard** [comment]
Thank you for reporting this error.
The fix will be included in the next version
