### ISSUE TITLE
PowerDNS timestamp nanoseconds off by a factor of 1000

### ISSUE THREAD

**Issue by ruffy91** [dmachard/go-dnscollector#360]
When decoding PowerDNS protobuf logs the timestamps always are yyyy-mm-dd[T]hh:mm:ss.**000**SSSSSSZ
This is because the timestamps powerdns uses are in usec and they are stored in the DnsMessage objects as nsec without conversion here:

https://github.com/dmachard/go-dnscollector/blob/2e1b20302c18e560cf5354454611419e0895f8d3/collectors/powerdns_processor.go#L203

Please add a conversion factor (* 1e3) to fix this issue.

**Comment by dmachard** [comment]
Thank to catch up this issue.
The fix will be in the next release v0.34.
