### ISSUE TITLE
Elasticsearch bulk insert

### ISSUE THREAD

**Issue by AlexDF2017** [dmachard/go-dnscollector#374]
Please implement bulk insert (POST) for Elasticsearch target, for performance reason. If possible include a parameter to tune the amount of messages to be grouped in single bulk operation. Thanks. AlexDF

**Comment by arvchristos** [comment]
This is totally needed in any context with many logs. I just pushed my approach on bulk indexing for ES in #382 . Any feedback is welcome!

**Comment by dmachard** [comment]
beta release available with bulk support https://github.com/dmachard/go-dnscollector/releases/tag/v0.35.0-beta2
thanks to @arvchristos
