### ISSUE TITLE
SIGHUP is not triggering a reload of transformers

### ISSUE THREAD

**Issue by arvchristos** [dmachard/go-dnscollector#375]
Hello,

Thank you for the wonderful project. 

It seems that sending a SIGHUP to the go-dnscollector process is not triggering a full config reload. In particular, I tested this by setting a file in `keep-domain-file` transform, testing that this works, then adding a new domain there and sending a SIGHUP. Then, the newly added domain was not taken into account. 

Is this by design ? This functionality would really help us fetching lists from various sources (e.g. MISP) and triggering a reload for the config.

Thank you in advance!

**Comment by dmachard** [comment]
Hi, 
Thanks for your support.

The config reload is partial right now, all settings referring to an external file are not reloaded .
I will take a look to see how to properly reload all actives transforms on SIGHUP and come back to you.

In meantime, any contributions are welcome to improve this project :)

**Comment by dmachard** [comment]
FYI, full reload of the configuration is  planned for next release

**Comment by dmachard** [comment]
beta release available https://github.com/dmachard/go-dnscollector/releases/tag/v0.38.0-beta1
Any feedback will be appreciated!
