### ISSUE TITLE
support golang 1.21

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dnscollector#378]

**Comment by mikeS7** [comment]
May be related:
`panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use.
goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        /go/pkg/mod/go4.org/unsafe/assume-no-moving-gc@v0.0.0-20230204201903-c31fa085b70e/untested.go:25 +0x1a0`

I've got the error when compiled with go 1.21.0 as pointed in Dockerfile.
In the past there were similar issue for 1.19 #112

**Comment by Abhicodeitout** [comment]
Yeah @mikeS7  we  can add similar changes  like we did for 1.19
