### ISSUE TITLE
Logger: redispubsub - redis answers are not read.

### ISSUE THREAD

**Issue by gallypette** [dmachard/go-dnscollector#410]
Oversight from me: redis returns an integer when one `PUBLISH` data on a pubsub channel (https://redis.io/commands/publish/).
So `go-dnscollector` process's `Recv-Q` grows until its limits, then redis process's `Send-Q` grows to its limit and then `go-dnscollector` hangs.

PR incoming.

**Comment by gallypette** [comment]
BTW `loggers/tcpclient.go` suffers from the same issue.

**Comment by dmachard** [comment]
Thanks to catch that.  it's can be also related to #353  ?
I will take a look to backport your fix to other loggers.

**Comment by gallypette** [comment]
It should not be related to #353 as it clogs the OS TCP stack.
I am wondering if #353 is still an issue though, we started running a bigger collector over the week end and it is using around 320MB RSS with no ramping up in sight. I will know better as time passes.

**Comment by dmachard** [comment]
Thanks.
Any feedbacks regarding memory, cpu usage or performance will be really appreciated.

**Comment by gallypette** [comment]
500MB after a day. I am unsure whether there is really an issue. I rewrote this part to remove allocations from the flush loop. This should already be better.
If that the case I will push the changes to this branch directly.
