### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/go-dnscollector#434]
Hi there,

Could you please a little improve logging:

```
ERROR: 2023/10/23 09:59:18.733086 [tap] transformer=normalize - ICANN Unmanaged
ERROR: 2023/10/23 09:59:20.256797 [tap] transformer=normalize - ICANN Unmanaged
ERROR: 2023/10/23 09:59:20.256869 [tap] transformer=normalize - ICANN Unmanaged
ERROR: 2023/10/23 09:59:21.411362 [tap] transformer=normalize - ICANN Unmanaged
```

not obvious, for which domain name I got an error

https://github.com/dmachard/go-dnscollector/blob/22e74235b32ea40ea3fc4b62015fc0b4254f02bf/transformers/normalize.go#L171C4-L171C4

Thank you.

**Comment by dmachard** [comment]
beta release available https://github.com/dmachard/go-dnscollector/releases/tag/v0.38.0-beta1
Any feedback will be appreciated!
