### ISSUE TITLE
tcpclient flush-interval doesn't appear to be honoured

### ISSUE THREAD

**Issue by mattb-nn** [dmachard/go-dnscollector#450]
Hi,

I'm reading from a powerdns-recursor and sending to a unix domain socket.  All is going well, but I was hoping that the flush-interval setting on the `tcpclient` logger would minimise the delay between message received into go-dnscollector and it being received on the other side of the socket.

No matter what i set the configuration value to, it always seems to take 30s to appear on the other side of the socket.

I think there may be a typo in the TcpClient logger at the following link, and that reference to the fluentd logger should be replaced with a TcpClient logger.

https://github.com/dmachard/go-dnscollector/blob/855852e280eb177a57afa38d09895ab6698fb90a/loggers/tcpclient.go#L309C48-L309C48

**Comment by dmachard** [comment]
Thank to report that
Can you test the beta release 0.38.0-beta 2?
