### ISSUE TITLE
Feature request: extend Prometheus metrics by adding tld-plus-one statistics

### ISSUE THREAD

**Issue by steffann** [dmachard/go-dnscollector#453]
We have been using a very old version of go-dnscollector, and we are unable to upgrade to the latest version because nothing similar to the `etldplusone_top_total` statistics seems to be available on the Prometheus endpoint anymore.

The old `tld_top_total` and `etld_top_total` distinction was very useful to us as well, but they seem to be mixed into `top_tlds`. It would be nice to get that back too, but it's is something we can live without.

So here a request to bring something similar to `etldplusone_top_total` back :)

If you can give me a pointer to what needs to be done I'd be happy to help!

**Comment by dmachard** [comment]
Thank to report.

 I think the metrics were deleted since v0.33, a major rewriting has been done in the prometheus logger in [v0.33.0](https://github.com/dmachard/go-dnscollector/releases/tag/v0.33.0) by me and https://github.com/dmachard/go-dnscollector/releases/tag/v0.34.0 by @kabenin 

I will take a look to introduce again theses metric.

**Comment by kabenin** [comment]
Sorry for deleting this metric.
@dmachard, I'll try to fix this asap.

**Comment by kabenin** [comment]
Hi @dmachard, I created a PR that introduces etldplusone_total and etldplusone_top metrics.

**Comment by johnhtodd** [comment]
Not to divert this useful patch, but it seems that what this really is interested in is not the distance from the TLD, but the distance from a relevant "important" part of the domain name.  Would this be more powerful if it could record zero through N (specifiable) splits from the left side of a domain found in a list that would look suspiciously like the public suffix list? (https://publicsuffix.org/)  That way, an administrator could with some accuracy define what they were interested in seeing as summary data.  In a perfect world, this would also have "include" and "exclude" syntax, in a way that would support ordered executions of those expressions.
