### ISSUE TITLE
DNS Queries and responses are not logged 

### ISSUE THREAD

**Issue by HesaMtiPu** [dmachard/go-dnscollector#459]
DNS Queries and responses are not logged.
Config.yml:-
global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        sock-path: /tmp/dnstap.sock

  loggers:
  - name: relay-out2
      dnstap:
        remote-address: 10.X.X.X
        remote-port: 9990

  - name: file
     logfile:
        enable: true
        file-path:  "/var/run/dnscollector/dnstap.log"
        max-size: 100
        max-files: 10
        mode: text

  routes:
    - from: [ tap ]
      to: [ relay-out2 , file ]

+++++++++++
Dns-Collector Version =0.37.0
++++++++++++++++++++++++
[tap] collector=dnstap - starting collector...
[tap] collector=dnstap - running in background...
[tap] collector=dnstap - is listening on unix:///tmp/dnstap.sock
[relay-out2] logger=dnstap - running in background...
 [relay-out2] logger=dnstap - connecting to 10.X.X.X:9990
[file] logger=file - running in background...
[relay-out2] logger=dnstap - ready to process
 [file] logger=file - ready to process
 [relay-out2] logger=dnstap - transport connected with success
  [relay-out2] logger=dnstap - framestream initialized with success
+++++++++++
i want to logged dns query in text file but not able to logged.
how can i troubleshoot this issue.
kindly suggest..

**Comment by dmachard** [comment]
Can you try to log the console and share the output ?
Your dns server is properly configured to send logs to your  dnstap.sock ?

**Comment by HesaMtiPu** [comment]
Thanks For your reply...
I just got that type of output from console.
 17:51:28.241612 [tap] collector=dnstap - starting collector...
 17:51:28.241691 [tap] collector=dnstap - running in background...
 17:51:28.242186 [tap] collector=dnstap - is listening on unix:///tmp/dnstap.sock
 17:51:28.242254 [relay-out2] logger=dnstap - running in background...
 17:51:28.242742 [relay-out2] logger=dnstap - connecting to 10.x.x.x:9990
 17:51:28.242969 [file] logger=file - running in background...
 17:51:28.243064 [relay-out2] logger=dnstap - ready to process
 17:51:28.243111 [file] logger=file - ready to process
 17:51:28.243232 [relay-out2] logger=dnstap - transport connected with success
 17:51:28.243793 [relay-out2] logger=dnstap - framestream initialized with success
++++++++++++++++++++++++++++++++++++++++
and yes our DNS Server is properly configured. because in our one Vms dns server send logs to dnstap successfully, but in our second Dns server not able to send data to dnstap.sock with same configuration. that why i am confused why this happening with second VMs. 
and in our DNS query logs file is also showing that connection is established successfully but not able to send logs.
Kindly suggest .

**Comment by dmachard** [comment]
Based on your logs, it appears that there is no connection to the dnstap.sock from the DNS server. 
Could there be an issue with permissions?

**Comment by dmachard** [comment]
When a connection is made to dnstap.sock, you should obtain the following logs:

INFO: 2023/11/18 15:46:59.056859 [tap] collector=dnstap#3 - **new connection from @**
INFO: 2023/11/18 15:46:59.056874 [tap] processor=dnstap#3 - initialization...
INFO: 2023/11/18 15:46:59.057229 [tap] processor=dnstap#3 - waiting dns message to process...

**Comment by HesaMtiPu** [comment]
Thanks for your help @dmachard Sir...
