### ISSUE TITLE
The problem is that this can be slow every time bind is restarted

### ISSUE THREAD

**Issue by HackBeiChen** [dmachard/go-dnscollector#461]
I used bind9.18.16, used dnstap to send sock files generated by dnscontroller, and then used dnscontroller to send syslogs to the log server. The problem is that this can be slow every time bind is restarted, and the log that sees /var/log/messages stays on Nov 13 10:15:08 dns-manager named[28439]: dnstap: closing dnstap, wait a minute to stop, start quickly. If you turn off dnscontroller first, then restarting bind9 will be very fast. What is the reason?

**Comment by dmachard** [comment]
Can you share the config.yml of your dnscollector ?
And the version used

**Comment by HackBeiChen** [comment]
The version is go-dnscollector_0.37.0,  
Here are the main configurations:

global:
  # If turned on, log some applications messages
  trace:
    # debug informations
    verbose: true
    # log malformed packet
    # log-malformed: false
    # # filename is the file to write logs to.
    # filename: ""
    # # maximum size in megabytes of the log file it gets rotated
    # max-size: 10
    # # maximum number of old log files to retain
    # max-backups: 10

  # Set the server identity name
  # comment the following line to use the hostname
  server-identity: "dns-collector"
  text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length qname qtype latency"
  # default text field delimiter
  text-format-delimiter: " "
  # default text field boundary
  text-format-boundary: "\""

# create your dns collector, please refer bellow to see the list
# of supported collectors, loggers and transformers
multiplexer:
  collectors:
    - name: tap
      dnstap:
        sock-path: /usr/local/bind-light/chroot/named/var/run/dnstap.sock

  loggers:
    - name: syslog_server
      syslog:
        severity: INFO
        facility: DAEMON
        transport: udp
        remote-address: "172.19.100.166:51400"
        retry-interval: 10
        text-format: ""
        mode: json
        tls-support: false
        tls-insecure: false
        format: ""
        chan-buffer-size: 65535
        tag: "MSGID"

  routes:
    - from: [ tap ]
      to: [ syslog_server ]

**Comment by dmachard** [comment]
Thank you for reporting it.

Reproduced in my side with bind 9.18.19 and DNScollector v0.38.0.

More investigation is required to understand what might be going wrong during the closure of dnstap.

**Comment by HackBeiChen** [comment]
Thank you for your help !
