### ISSUE TITLE
Convert all domain names to lower case

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/go-dnscollector#5]
I found that this wonderful magic tool was extended by new metrics, which possible to retrieve over curl, but also I found duplicate for some domains
```
dnscollector_domains_slow_top{stream="global",domain="INVErITA.COM"} 2
dnscollector_domains_slow_top{stream="global",domain="INVERItA.COM"} 2
dnscollector_domains_slow_top{stream="global",domain="iNvErITA.COM"} 2
```

everything of this is the same domain, it will be good to have an option in configuration file, which convert all domain to lowercase or upper case.

**Comment by dmachard** [comment]
implemented in release v0.11.0
