### ISSUE TITLE
Prometheus stats on ops per second per pipeline

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#512]
**Is your feature request related to a problem? Please describe.**
There is a general counter (per stream) of "dnscollector_throughput_ops" and "dnscollector_throughput_ops_max".  This may not make sense in a pipeline model and is too broad to capture meaningful data that is useful for diagnosing how flows are operating within go-dnscollector, and it would be very helpful to understand what the throughput was per pipeline stanza.

**Describe the solution you'd like**
Using the config file from https://github.com/dmachard/go-dnscollector/issues/510 this is what perhaps the sections would look like:

```
dnscollector_throughput_ops_max{pipeline="all-data"} 3395
dnscollector_throughput_ops{pipeline="all-data"} 1943
dnscollector_throughput_ops_max{pipeline="apple-only"} 5
dnscollector_throughput_ops{pipeline="apple-only"} 2
dnscollector_throughput_ops_max{pipeline="outputfile"} 3390
dnscollector_throughput_ops{pipeline="outputfile"} 1934
dnscollector_throughput_ops_max{pipeline="dnsdist-receiver-from-prod-machines"} 3395
dnscollector_throughput_ops{pipeline="dnsdist-receiver-from-prod-machines"} 1943

```

**Describe alternatives you've considered**
No other alternatives seem viable.

**Comment by dmachard** [comment]
It will be implemented in next release with global prometheus metrics. More details on PR #724 

![image](https://github.com/dmachard/go-dnscollector/assets/5562930/8e37f679-4950-4c9b-acd9-3221bffe689d)
