### ISSUE TITLE
Feature request: normalize lowercase RR's 

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#525]
**Is your feature request related to a problem? Please describe.**
There is a very useful normalize feature for the qname, but this doesn't appear to apply to the RR's that may be attached to a NOERROR response. Data being pushed out of this system is being put into other platforms and comparisons are done against them.  DNS doesn't care about upper/lowercase but databases do, or at least the processing power put into databases being case-agnostic is power that is usually not well-spent at the core.  Having the ability for all DNS data being lowecased will save a lot of post-processing before database ingest.

**Describe the solution you'd like**
It would be useful to apply lowercase to rr's as a transform with a config option:
 
`  rr-lowercase: true`

Also, keep in mind that if the RR has an rdatatype of "SOA" then it should be the case that lowercase is applied to the content in the name and the rdata fields. I think that's the only field that should have lowercase applied inside the rdata field also, though I haven't thought about that enough probably.

**Describe alternatives you've considered**
Could have the database downcase, but that takes a lot of resources centrally; the goal is to have this work done at the edge.

**Comment by dmachard** [comment]
feature implemented in next release
