### ISSUE TITLE
Parse "policy" fields in dnstap messages

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#530]
**Is your feature request related to a problem? Please describe.**
The DNSTAP parser seems to be fairly complete, but is missing one significant section: the policy parsing components.  (https://github.com/dnstap/dnstap.pb/blob/master/dnstap.proto) These at least should be parsed and made available for matching or output to the various handlers.

**Describe the solution you'd like**
Make the "Policy" fields available to matching engine components and all output streams/paths.

**Comment by dmachard** [comment]
It will be implemented in the next release. Can you tell me which DNS server has implemented that in DNStap? I can't seem to find it.
