### ISSUE TITLE
Expose "class" for objects

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#531]
**Is your feature request related to a problem? Please describe.**
While it is infrequent, there is a need to understand the "class" value for queries (IN, CH, etc.) - it would be good for completeness to have this as an output field.  While it may be seen as "almost always" set to "IN", it is not always the case and debugging for DOS attacks need full understanding of class.  

**Describe the solution you'd like**
Add "class" as a field under "dns" results.

**Additional context**
The additional data weight of one field could be counteracted by implementation of https://github.com/dmachard/go-dnscollector/issues/527 which would allow removal of field data before forwarding on to next steps in the pipeline or to other destinations.

**Comment by johnhtodd** [comment]
To be clear: this would apply not just for queries, but also for rr sets as well.

**Comment by dmachard** [comment]
Same as for #534, the class is decoded but not exposed 

```
type DNSAnswer struct {
	Class     int    `json:"-" msgpack:"-"`
}
```

Will be fix for future version

**Comment by dmachard** [comment]
completed in next release v0.42
