### ISSUE TITLE
Expose "cd" bit for objects

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#533]
**Is your feature request related to a problem? Please describe.**
The "cd" bit is not apparent in any output and is useful for completeness.

**Describe the solution you'd like**
Add "cd" flag for all queries in the "dns" section.

**Additional context**
Mostly the same comments as https://github.com/dmachard/go-dnscollector/issues/531

**Comment by dmachard** [comment]
Same explanation as #531 . This is evidently an oversight; while the CD flag is decoded, it is not currently exposed to the JSON model.
