### ISSUE TITLE
Expose "id" for objects

### ISSUE THREAD

**Issue by johnhtodd** [dmachard/go-dnscollector#534]
**Is your feature request related to a problem? Please describe.**
The "id" data is not apparent in any output and is useful for completeness.

**Describe the solution you'd like**
The "id" data is not apparent in any output and is useful for completeness.

**Additional context**
Mostly the same comments as https://github.com/dmachard/go-dnscollector/issues/531

**Comment by dmachard** [comment]
Id is not currently exported to JSON model but available in the internal DNSMessage

```golang
type DNS struct {
         ....
	ID      int    `json:"-" msgpack:"-"`
        ....
}
```

Will be fix for future version
