### ISSUE TITLE
Dashboard - /grafana_prometheus.json

### ISSUE THREAD

**Issue by M3D3** [dmachard/go-dnscollector#566]
When uploading to Grafana, Dashoboard gives an error :
invalid parameter "match[]": match[] must contain at least one non-empty matcher

![изображение](https://github.com/dmachard/go-dnscollector/assets/94751275/76d3008b-914c-40b3-b410-a3664d887b0a)

**Comment by M3D3** [comment]
If you remove the variables, everything works. Could you please tell me how to fix the variables?
![изображение](https://github.com/dmachard/go-dnscollector/assets/94751275/bac5b25b-6024-4775-a73f-2f07317bedf1)

**Comment by dmachard** [comment]
Can you give more details?
What variables are you talking about?

**Comment by M3D3** [comment]
Thanks, I found the problem, it's working.
