### ISSUE TITLE
Output details of RPZ policy applied 

### ISSUE THREAD

**Issue by mattb-nn** [dmachard/go-dnscollector#572]
Currently, in the case of a PowerDNS protobuf message to which an RPZ policy has been applied, the only detail about the applied policy is whether it was triggered by RPZ or Lua.  This is omitting a lot of very useful information which is included in the PowerDNS protobuf schema.

I would like to output all the detail available relating to the RPZ policy, such as:
- appliedPolicyType
- appliedPolicyTrigger
- appliedPolicyHit
- appliedPolicyKind

**Comment by agjmills** [comment]
This would be a super-useful feature, as I have a similar requirement - including this functionality in go-dnscollector is certainly preferable to me, than maintaining a separate shim (or something) between powerdns and go-dnscollector

**Comment by dmachard** [comment]
It will be supported in the next release.

---

_If you find the project helpful, please consider supporting the project via monthly donation via [GitHub Sponsors](https://github.com/sponsors/dmachard) or simply add a star to this project._
