### ISSUE TITLE
read dnstap stream from files not more working

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dnscollector#602]
**Describe the bug**
read dnstap stream from files not more working

**To Reproduce**
go run . -config docs/_examples/use-case-14.yml

**Comment by romainw** [comment]
For the record we do exactly this with 0.41.0 and reading/processing the dnstap files works for us out of the box.
```
INFO: 2024/03/08 05:33:35.595222 collector - [dnstap-dns-server-1] fileingestor - processing of [dnstap-2024-03-07-20:56:53.fstrm] terminated
INFO: 2024/03/08 05:33:35.595416 collector - [dnstap-dns-server-1] fileingestor - delete file [dnstap-2024-03-07-20:56:53.fstrm]
IN
```

**Comment by dmachard** [comment]
It's good to hear thanks, so it's just something wrong with my example.
