### ISSUE TITLE
Can't build for arm 32 bit

### ISSUE THREAD

**Issue by mikeS7** [dmachard/go-dnscollector#619]
I've got the error when build for arm platform.

`22.36 # github.com/dmachard/go-dnscollector/dnsutils`
`22.36 dnsutils/message.go:814:32: math.MaxUint32 (untyped int constant 4294967295) overflows int`
`22.36 dnsutils/message.go:824:32: math.MaxUint32 (untyped int constant 4294967295) overflows int`

Run the following in docker:
`RUN GOOS=linux GOARCH=arm CGO_ENABLED=0 go build -ldflags "-s -w -X main.version=0.41.0" -o /go/bin/go-dnscollector`

**Comment by dmachard** [comment]
Did it work well before version 0.41.0?

**Comment by mikeS7** [comment]
I've got such errors started from 0.40.1. Last version without error is 0.40.0

**Comment by dmachard** [comment]
Thank, 

I think it related to the change introduced in v0.40.2 to fix the following code scanning alert:

`Incorrect conversion of an integer with architecture-dependent bit size from to a lower bit size type uint16 without an upper bound check.`

![image](https://github.com/dmachard/go-dnscollector/assets/5562930/1aab2c59-61ac-41a7-9d3d-48eed37b3d6d)

**Comment by dmachard** [comment]
I don't have access to an arm 32b platform, but I can reproduce with linux/386

```
52.44 # github.com/dmachard/go-dnscollector/dnsutils
52.44 dnsutils/message.go:814:32: math.MaxUint32 (untyped int constant 4294967295) overflows int
52.44 dnsutils/message.go:824:32: math.MaxUint32 (untyped int constant 4294967295) overflows int
```

**Comment by dmachard** [comment]
Fixed in main branch but tested only with linux/386 platform.
Any feedback will be appreciated.
