### ISSUE TITLE
Implement new domain tracking

### ISSUE THREAD

**Issue by dmachard** [dmachard/go-dnscollector#628]
**Is your feature request related to a problem? Please describe.**

Implement new domain tracking like https://doc.powerdns.com/recursor/settings.html#new-domain-log

https://doc.powerdns.com/recursor/nod_udr.html#newly-observed-domain

**Comment by Jon1760** [comment]
I'm not the original requestor but this caught my eye.

While I currently obtain the data in a different way (post-processing of DNS query logs), particularly as my use case does not require real-time actions, and I outsource some aspects of the problem to a third party DNS security filtering service, generally this is useful for building up white or black lists of domains that are allowed or blocked at the perimeter and/or doing security analysis on "new" domains that are used.

I'd consider using the feature if it existed.

**Comment by dmachard** [comment]
implementation in progress

**Comment by dmachard** [comment]
implemented in next release v1.3.0
