### ISSUE TITLE
Implement PID File for go-dnscollector to Enable SIGHUP Configuration Reload

### ISSUE THREAD

**Issue by 4quarks** [dmachard/go-dnscollector#722]
### Implement PID File for go-dnscollector to Enable SIGHUP Configuration Reload

**Description:**
Now that SIGHUP is implemented on the go-dnscollector side ([see](https://github.com/CERN-CERT/pDNSSOC/issues/19)), we ([pDNSSOC](https://github.com/CERN-CERT/pDNSSOC)) need to integrate this functionality for configuration reload without restarting the process. This will allow us to make changes on-the-fly, such as reading updated files, by sending a SIGHUP signal to the process without having to restart the process manually.

**Background:**
It became common practice for daemonized processes to use SIGHUP for configuration reload. This allows changes to be made without terminating the process. 

**Current Implementation Steps:**
1. Find the process number of go-dnscollector.
2. Run the following command to reload the configuration:
   ```bash
   kill -SIGHUP 21371  # Assuming 21371 is the PID of the running go-dnscollector
   ```

**Challenge:**
The PID changes every time the process restarts, which makes it difficult to automate this with a static command.

**Proposed Solution:**
Implement a PID file in go-dnscollector that stores the current PID of the running process. This PID file will be created on startup and can be referenced to send the SIGHUP signal.

**Benefits:**
- Simplifies the process of sending SIGHUP signals.
- Eliminates the need to restart the process for configuration changes.
- Potentially allows us to remove the dependency on supervisord, as it is currently used only for restarting on config changes.
- Follows a good and common industry practice.

**Additional Notes:**
- Confirm if Denis has implemented the PID file functionality. If not, this issue should prioritize that implementation.
- If we (pDNSSOC) can ditch supervisord, a Python script inside fetch-iocs can monitor file changes and send the SIGHUP signal accordingly.

**References:**
- [Run Program and Generate PID](https://kiennt.com/blog/2012/06/29/run-program-and-generate-pid.html)

**Action Items:**
- [ ] Implement PID file creation in go-dnscollector.
- [ ] We (pDNSSOC) will have to create a script to read the PID from the PID file and send the SIGHUP signal.

**Comment by 4quarks** [comment]
This sounds perfect for us. Thanks!

**Comment by dmachard** [comment]
feature implemented in master branch

**Comment by 4quarks** [comment]
The issue seems to be resolved. Thanks for your quick action!
