### ISSUE TITLE
rdata for format: text

### ISSUE THREAD

**Issue by csszep** [dmachard/go-dnscollector#9]
Please add rdata to text-format fields.

Thx 
csszep

**Comment by dmachard** [comment]
Hi,
Can you more give more details about what you expect ? just the first rdata available in the response ?
Denis

**Comment by csszep** [comment]
Hi!
If the syslog output will know the json format with all rdata answers, then it is not necessary for me.

**Comment by dmachard** [comment]
Indeed, with the json format all rdata answers are available. I made the change to support also json with the syslog output.

**Comment by dmachard** [comment]
a new *answer* directive is added but it's limited to the first answer only
prefer to use JSON if you want the all answers.
