### ISSUE TITLE
flat-json filtering 

### ISSUE THREAD

**Issue by Resha777** [dmachard/go-dnscollector#906]
I'm currently using dnsdist to send quires to dnstap then forward them to kafka in flat-json mode , there are many fields that i don't want and it seems that there is no way to do that, like i only want to send ( dns.qname , dns.qtype , dnstap.timestamp-rfc3339ns ) , it seems that i can only do that in text mode , i want to to that in flat-json and send it to my kafka

**Comment by dmachard** [comment]
Can you try the relabeling transform?

https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers/transform_relabeling.md
